### ISSUE TITLE
Windows test failure

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-geoip#14]
```
11) LogStash::Filters::GeoIP correct encodings with default db "{"ip":"1.1.1.1"}" when processed
     Failure/Error: pipeline.instance_eval { @filters.each(&:register) }
     TypeError:
       can't convert nil into String
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'
```

Lots of test failures, actually.

See https://github.com/elasticsearch/logstash/issues/2487 for the full run output

**Comment by ph** [comment]
fixed in the latest https://github.com/elasticsearch/logstash/tree/wip/bundler-move
The vendor files are correctly installed and I have no other test failing.
